name: Automated ISPU Preprocessing

on:
  push:
    paths:
      - "namadataset_raw/**"
      - "preprocessing/automate_Asrafatin Nabillah.py"
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install dependency
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    # 4. Jalankan preprocessing
    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Asrafatin Nabillah.py

    # 5. Commit hasil preprocessing (opsional tapi ADVANCE)
    - name: Commit preprocessing results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add preprocessing/namadataset_preprocessing/
        git commit -m "Auto preprocessing dataset [GitHub Actions]" || echo "No changes to commit"
        git push
